apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-webserver
  name: my-webserver
  namespace: my-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-webserver
  strategy: {}
  template:
    metadata:
      labels:
        app: my-webserver
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - image: nginx:alpine
        name: nginx
        resources:
          limits:
            memory: 100Mi
            cpu: 500m
          requests:
            memory: 50Mi
            cpu: 250m
        securityContext:
          readOnlyRootFilesystem: true
